export const ACTN_ADD_TODO = 'ADD_TODO';
export const ACTN_TOGGLE_TODO = 'TOGGLE_TODO';
export const ACTN_FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const ACTN_FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const ACTN_FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';
export const ACTN_ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
// export const ACTN_SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
