export const ACTN_ADD_TODO = 'ADD_TODO';
export const ACTN_TOGGLE_TODO = 'TOGGLE_TODO';
export const ACTN_RECEIVE_TODOS = 'RECEIVE_TODOS';
export const ACTN_REQUEST_TODOS = 'REQUEST_TODOS';

// export const ACTN_SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
